version: 1.0.{build}

branches:
  only:
  - master
  - /.*appveyor.*/

environment:
  STACK_ROOT: C:\sr
  STACK_VERSION: 1.9.3
  STACK_YAML: stack.yaml

install:
  - cmd: >-
      choco install -y haskell-stack --version %STACK_VERSION%
      stack setup > nul
      stack path

cache:
  - C:\sr
  - .stack-work

build_script:
  - cmd: stack build

test_script:
  - cmd: >-
      stack test dhall:tasty
      stack test dhall-json
      stack test dhall-text
      stack test dhall-bash

before_deploy:
  - cmd: stack install

artifacts:
- path: '%APPDATA%\local\bin\dhall.exe'
  name: dhall

    
deploy:
  - provider: GitHub
    auth_token:
      secure: Gs/tiz6Jtg/Zjd4zGHDhuSv4Y9a+zJ574LWwzOe2bvZNGX/M8XupkxdGmBpDlnOf
    artifact: "dhall"
    on:
      APPVEYOR_REPO_TAG: true
