version: 1.0.{build}

branches:
  only:
  - master
  - /.*appveyor.*/

environment:
  STACK_ROOT: C:\sr
  STACK_VERSION: 1.9.3
  STACK_YAML: stack.yaml

install:
  - choco install -y haskell-stack --version %STACK_VERSION%
  - stack setup > nul

cache:
  - C:\sr
  - .stack-work

build_script:
  - stack build
  - stack install --local-bin-path bin
  
test_script:
  - stack test dhall:tasty
  - stack test dhall-json
  - stack test dhall-text
  - stack test dhall-bash

artifacts:
- path: 'bin\dhall.exe'
  name: dhall

    
deploy:
  - provider: GitHub
    auth_token:
      secure: Gs/tiz6Jtg/Zjd4zGHDhuSv4Y9a+zJ574LWwzOe2bvZNGX/M8XupkxdGmBpDlnOf
    artifact: dhall
    on:
      APPVEYOR_REPO_TAG: true
