version: 1.0.{build}

branches:
  only:
  - master
  - appveyor

environment:
  STACK_VERSION: 1.9.3
  STACK_YAML: stack.yaml

install:
  - cmd: >-
      choco install -y haskell-stack --version %STACK_VERSION%
      stack setup

cache:
  - C:\sr
  - .stack-work

build_script:
  - cmd: stack build

test_script:
  - cmd: >-
      chcp 65001
      stack test
