resolver: lts-12.16
packages:
  - dhall
  - dhall-bash
  - dhall-json
  - dhall-text
extra-deps:
  - megaparsec-7.0.3
  - repline-0.2.0.0
  - serialise-0.2.1.0
  - neat-interpolation-0.3.2.4
  - dotgen-0.4.2@sha256:309b7cc8a3593a8e48bee7b53020d5f72db156d58edf78a0214f58fbb84b292b
nix:
  packages:
    - ncurses
    - zlib
