resolver: lts-12.4
extra-deps:
  - megaparsec-7.0.0@rev:0
  - repline-0.2.0.0@rev:0
  # Version 0.2.0.0 of cborg, the latest on Hackage, is broken on i386.
  - github: well-typed/cborg
    commit: master
    subdirs:
      - cborg
      - serialise
nix:
  packages:
    - ncurses
    - zlib
