name: action
on: [push]
#on:
#  push:
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'
#      - '[0-9]+.[0-9]+.[0-9]+[0-9]+'
jobs:
  deploy macOS:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    name: Deploy ${{ matrix.os }} executable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1.2.1
        with:
          enable-stack: true
      - run: stack build
