name: action
on: [push]
#on:
#  push:
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'
#      - '[0-9]+.[0-9]+.[0-9]+[0-9]+'
jobs:
  deploy:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    name: Deploy ${{ matrix.os }} executable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: setup-haskell-cabal
        uses: haskell/actions/setup@v1.2.1
        with:
          enable-stack: true
      - run: stack build
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.stack-root }}
            .stack-work
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-
