name: main
on: [push]
#on:
#  push:
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'
#      - '[0-9]+.[0-9]+.[0-9]+[0-9]+'
jobs:
  deploy:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    name: Deploy ${{ matrix.os }} executable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - id: setup-haskell-cabal
        uses: haskell/actions/setup@v1.2.1
        with:
          enable-stack: true
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.stack-root }}
            .stack-work
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: stack build
      - run: stack build --copy-bins --local-bin-path ./bin
      - if: ${{ matrix.os == 'macOS-latest' }}
        run: |
          mkdir -p share/man/man1
          cp dhall/man/dhall.1 share/man/man1/
          cp dhall-docs/src/Dhall/data/man/dhall-docs.1 share/man/man1/
      - if: ${{ matrix.os == 'macOS-latest' }}
        uses: ./.github/actions/package
        with:
          cabal-name: dhall
          os: macos
          assets: >
            bin/dhall
            share/man/man1/dhall.1
      - if: ${{ matrix.os == 'macOS-latest' }}
        uses: ./.github/actions/package
        with:
          cabal-name: dhall-bash
          os: macos
          assets: bin/dhall-to-bash
      - if: ${{ matrix.os == 'macOS-latest' }}
        uses: ./.github/actions/package
        with:
          cabal-name: dhall-docs
          os: macos
          assets: >
            bin/dhall-docs
            share/man/man1/dhall-docs.1
      - if: ${{ matrix.os == 'macOS-latest' }}
        uses: ./.github/actions/package
        with:
          cabal-name: dhall-json
          os: macos
          assets: >
            bin/dhall-to-json
            bin/dhall-to-yaml
            bin/json-to-dhall
      - if: ${{ matrix.os == 'macOS-latest' }}
        uses: ./.github/actions/package
        with:
          cabal-name: dhall-lsp-server
          os: macos
          assets: bin/dhall-lsp-server
      - if: ${{ matrix.os == 'macOS-latest' }}
        uses: ./.github/actions/package
        with:
          cabal-name: dhall-nix
          os: macos
          assets: bin/dhall-to-nix
      - if: ${{ matrix.os == 'macOS-latest' }}
        uses: ./.github/actions/package
        with:
          cabal-name: dhall-openapi
          os: macos
          assets: bin/openapi-to-dhall
      - if: ${{ matrix.os == 'macOS-latest' }}
        uses: ./.github/actions/package
        with:
          cabal-name: dhall-yaml
          os: macos
          assets: >
            bin/dhall-to-yaml-ng
            bin/yaml-to-dhall
